#!/bin/bash
#h-------------------------------------------------------------------------------
#h
#h Name:         params
#h Type:         Linux shell script
#h Purpose:      parameters for MxBash
#h Project:      z-Way Homeserver
#h Installation: rename the file params_template to params,
#h               and enter your parameters
#h
#h-------------------------------------------------------------------------------

# for to display the zway jobqueue the administrator login is necessary:
#USERPW=admin:secret

# for backup and restore it's necessary to define the backup path:
#BACKUP_PATH=/media/zway/backup

# if you want to display a sockets statistics (for example for MQTT sockets):
#MQTT_PORT='1883'     
# separate multiple ports by space

# for lock/unlock Mx-modules at start (module MxBaseModule is necessary):
#MXLOCK=yes

# execute command before running each function:
#COMMAND_PRE='echo ==================================================================='
#COMMAND_PRE='clear'

